# Default values for portal-objetos-aprendizaje.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

mysql:
  enabled: true
  mysqlUser: "portal-objetos-aprendizaje"
  mysqlPasswordSecret: "poa-mysql-password-secret"
  mysqlDatabase: "portal-objetos-aprendizaje"
  mysqlTablePrefix: "qvkei_"
  # If mysql deployment is enabled
  existingPVClaim: "pvc-portable-objetos-aprendizaje-mysql"
  image:
    tag: "8"
    repository: mysql
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # If mysql deployment is not enabled
  mysqlHost: ""
  mysqlPort: 3306

kafka:
  enabled: true
  # If kafka deployment is enabled
  image:
    tag: "3.7"
    repository: bitnami/kafka
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  zookeeper:
    image:
      tag: "3.9"
      repository: bitnami/zookeeper
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources: {}
      # If you do want to specify resources (this will apply all the deployments), uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
  # If kafka deployment is not enabled
  kafkaHost: "override-kafka.host"
  kafkaPort: 9092

admin:
  # PublicURL is used for url generation and ingress if enabled
  publicUrl: "https://portal-objetos-aprendizaje-admin.k8s.local"
  appKeySecret: "poa-admin-appkey-secret"
  sessionLifetime: "120"
  colorPrimary: "#2C4C7E"
  colorSecondary: "#507AB9"
  generalErrorMessage: "Ha ocurrido un error"
  pwresTokenExpirationMin: "60"
  existingPVClaimPublic: "pvc-portable-objetos-aprendizaje-admin-public"
  existingPVClaimProtected: "pvc-portable-objetos-aprendizaje-admin-protected"
  image:
    tag: "latest"
    repository: ghcr.io/objetos-aprendizaje/portal-administracion
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
web:
  # PublicURL is used for url generation and ingress if enabled
  publicUrl: "https://portal-objetos-aprendizaje-web.k8s.local"
  appKeySecret: "poa-web-appkey-secret"
  sessionLifetime: "120"
  colorPrimary: "#2C4C7E"
  colorSecondary: "#507AB9"
  image:
    tag: "latest"
    repository: ghcr.io/objetos-aprendizaje/portal-web
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  # className: "traefik"
  pathType: ImplementationSpecific
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  admin:
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - portal-objetos-aprendizaje-admin.k8s.local
  web:
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - portal-objetos-aprendizaje-web.k8s.local

replicaCount: 1
# NOTE: HorizontalPodAutoscaler is not supported unless php session is stored in a shared storage
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployments (all) definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployments (all) definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Other optional configurations and advanced features
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
