{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal-objetos-aprendizaje.fullname" . }}-mysql-service
  labels:
    {{- include "portal-objetos-aprendizaje.labels" . | nindent 4 }}
    {{- include "portal-objetos-aprendizaje-mysql.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "portal-objetos-aprendizaje-mysql.selectorLabels" . | nindent 4 }}
{{- end }}