# This is the FMNT Ceres intermediate and root CA certificates
apiVersion: v1
kind: Secret
metadata:
  name: mainjobs-poa-fmnt-ca
data:
  ca.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUcyakNDQk1LZ0F3SUJBZ0lRUlY4NjRWd2h6YnBVVDRLcVIxSHIyekFOQmdrcWhraUc5dzBCQVFzRkFEQTcKTVFzd0NRWURWUVFHRXdKRlV6RVJNQThHQTFVRUNnd0lSazVOVkMxU1EwMHhHVEFYQmdOVkJBc01FRUZESUZKQgpTVm9nUms1TlZDMVNRMDB3SGhjTk1UUXhNREk0TVRFME9EVTRXaGNOTWpreE1ESTRNVEUwT0RVNFdqQkxNUXN3CkNRWURWUVFHRXdKRlV6RVJNQThHQTFVRUNnd0lSazVOVkMxU1EwMHhEakFNQmdOVkJBc01CVU5sY21Wek1Sa3cKRndZRFZRUUREQkJCUXlCR1RrMVVJRlZ6ZFdGeWFXOXpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QQpNSUlCQ2dLQ0FRRUFuU0FFSmkzN0xXa3d5OW1UZjZYbHJ0UndjdStVdmtWcjVZK3lDL202TTRZbHI0Ynh3TmpiCnRqKys4YjZKQmFiOXd5SGhrdFZTSUJhK2RpWWhmc0hzV1ZXZ2tPbFN6TklQcVRQS09tall0TDNVSnVvVzNBYnAKRE5aSkVWRmdFb2xrQ2c1MXdYS01qTzdPNUNmSndJQTNpVjJmYmVlUjRZQU9tcy8xbXFtMExTa3JXaXd3bFlGOQpWbjhhcXIvZUFuVC9kOEtkWUM1Wi85TWMxYXpXSFdON3pKNk1UZHVaOVBjVmpNbTcwaXZpSGFvaGdFVXU5NzliCnkyM2FjeDY5cTdxTFBqSGtZb0doZjJmdDF0UXFZbWpzOWljZ3dQaHJ6THl5MXp6WFl5MEhvZUZuczRiaTJOK00KQlRtcGYvaThIWk9LNkJ5M01TMlVsQ3NqWGhIaHphbXdSd0lEQVFBQm80SUN5RENDQXNRd0VnWURWUjBUQVFILwpCQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdIUVlEVlIwT0JCWUVGTEhVVDhRamVmcEVCUW5HCjZ6blA2RFd3dUNCa01JR1lCZ2dyQmdFRkJRY0JBUVNCaXpDQmlEQkpCZ2dyQmdFRkJRY3dBWVk5YUhSMGNEb3YKTDI5amMzQm1ibTEwY21OdFkyRXVZMlZ5ZEM1bWJtMTBMbVZ6TDI5amMzQm1ibTEwY21OdFkyRXZUMk56Y0ZKbApjM0J2Ym1SbGNqQTdCZ2dyQmdFRkJRY3dBb1l2YUhSMGNEb3ZMM2QzZHk1alpYSjBMbVp1YlhRdVpYTXZZMlZ5CmRITXZRVU5TUVVsYVJrNU5WRkpEVFM1amNuUXdId1lEVlIwakJCZ3dGb0FVOTMzRi9jVG9taHQzWktmMUhhRE0KdjRkZ21tMHdnZXNHQTFVZElBU0I0ekNCNERDQjNRWUVWUjBnQURDQjFEQXBCZ2dyQmdFRkJRY0NBUllkYUhSMApjRG92TDNkM2R5NWpaWEowTG1adWJYUXVaWE12WkhCamN5OHdnYVlHQ0NzR0FRVUZCd0lDTUlHWkRJR1dVM1ZxClpYUnZJR0VnYkdGeklHTnZibVJwWTJsdmJtVnpJR1JsSUhWemJ5QmxlSEIxWlhOMFlYTWdaVzRnYkdFZ1JHVmoKYkdGeVlXTnB3N051SUdSbElGQnl3NkZqZEdsallYTWdaR1VnUTJWeWRHbG1hV05oWTJuRHMyNGdaR1VnYkdFZwpSazVOVkMxU1EwMGdLQ0JETHlCS2IzSm5aU0JLZFdGdUxDQXhNRFl0TWpnd01Ea3RUV0ZrY21sa0xVVnpjR0hECnNXRXBNSUhVQmdOVkhSOEVnY3d3Z2Nrd2djYWdnY09nZ2NDR2daQnNaR0Z3T2k4dmJHUmhjR1p1YlhRdVkyVnkKZEM1bWJtMTBMbVZ6TDBOT1BVTlNUQ3hQVlQxQlF5VXlNRkpCU1ZvbE1qQkdUazFVTFZKRFRTeFBQVVpPVFZRdApVa05OTEVNOVJWTS9ZWFYwYUc5eWFYUjVVbVYyYjJOaGRHbHZia3hwYzNRN1ltbHVZWEo1UDJKaGMyVS9iMkpxClpXTjBZMnhoYzNNOVkxSk1SR2x6ZEhKcFluVjBhVzl1VUc5cGJuU0dLMmgwZEhBNkx5OTNkM2N1WTJWeWRDNW0KYm0xMExtVnpMMk55YkhNdlFWSk1SazVOVkZKRFRTNWpjbXd3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUl3OQpLTFRnZmczemJsemFYSGM5Z0dRZVR1a1N1TW5tc3Y4cmdLQjRQWVJNTEdXTEw5enhZeXZuM1ZKQjI2LzhGd3VNCm1vVHlDZFJkVnFLZStZSm13SVZlbkY3cWcrZDhSbzUrWCtaajdhdGk3MFpPSjJHVmdiMU5BajJwTkErWitlWnIKVnBVRG4zMUwrM3ppVGhMdnBBdEV0VHg2QVRGYkptRWdrcFIxQW5iV3p2dXN3d1VJTVVCc3BSMDJuaUNJenFDSgpWbTJ1MlV5OWtIdytkaUJKUnV3VllwcEJaYXZnbjdFQ05PK3ZLZUlBS1ptZStXTWQwWlFUaGtEUllJeEZGd1loCldGb2MxVEUrTGYwblZiRWE1ai92Nm9WY2F1UCsyZHlMakgvclRkVmhoNExuSS9ES1BHS0hkdVE4cVh1aGJ4Z2IKSWl1OGpCVC8wbjNkV1FQRkIzb3U5K3NIbGxUOXVTVVZHcnRLK0t5amdHTEg1b2U4aTRHT2JIN0dKVXRoa1V3RQpZekdpamcvV21Ldm0ramcwZ25sV1Q3SGlVMEs0ZkVXbGRJQmw5bk5haDEyeVNQVk42M3EvOGtDWFMzSlI4Y004CjJaZXN6TFZudFBzNjRpdFYyV0tya3JOQStMdHU0Wi9VVFk0bHVIK0lSZXZvOXJlVDY3OTBNUXZZckN3alNzdU4KRDRmWEk4Ni9tR0VTR3ZoYndFQ21waGU4TC9qVjB1WjAxeUk1bW1naGVkQnI1V3FLdjY0RW1JWE5GVloyMyttaAo4UkZDZ3FQWnNhdFZhVm9CUXExRmV2T2hQTWpFdnhpTWd6UFh2ZTJBM2dTbW5nL1VLRGNLR3pGYnlMK3ZlU1poCmRQODU0bVBrM0lQRUNZWkVOcUFZV1hqQmx0bThVRFJtVUJ0MXdwZ1IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRmd6Q0NBMnVnQXdJQkFnSVBYWk9OTUdjMnlBWWRHc2RVaEdrSE1BMEdDU3FHU0liM0RRRUJDd1VBTURzeApDekFKQmdOVkJBWVRBa1ZUTVJFd0R3WURWUVFLREFoR1RrMVVMVkpEVFRFWk1CY0dBMVVFQ3d3UVFVTWdVa0ZKCldpQkdUazFVTFZKRFRUQWVGdzB3T0RFd01qa3hOVFU1TlRaYUZ3MHpNREF4TURFd01EQXdNREJhTURzeEN6QUoKQmdOVkJBWVRBa1ZUTVJFd0R3WURWUVFLREFoR1RrMVVMVkpEVFRFWk1CY0dBMVVFQ3d3UVFVTWdVa0ZKV2lCRwpUazFVTFZKRFRUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUxweGdIcE1obTUvCnlCTnR3TVo5SEFDWGp5d01JN3NRbWtDcEdyZUhpUGliVm1yNzVudU9pNUtPcHlWZFdSSGJOaTYzVVJjZnFRZ2YKQkJja1dLbzNTaGpmNVRuVVYvM1h3U3lSQVpIaUl0UUR3Rmo4ZDBmc2p6NTBRN3FzTkkxTk9IWm5qckRJYnpBegpXSEZjdFBWcmJ0UUJVTGdUZm14S28wblJJQm51dk1BcEdHV24zdjd2M1FxUUllY2FaNUpDRUpoZlR6QzhQaHhGCnRCRFhhRUFVd0VENjUzY1hldVlMajJWYlBObWFVdHUxdlo1R3p6M3JrUVVDd0pheWRreE5FSlk3a3ZxY2Z3K1oKMzc0ak5VVWVBbHordGFpYm1TWGFYdk1pd3puMTVDb3UwOFlmeEd5cXhSeHFBUVZLTDlMRndhZzBKbDFtcGRJQwpJZmtZdHdiMVRwbHZxS3RNVWVqUFVCakZkOGc1Q1N4SmtqS1pxTHNYRjNtd1dzWG1vOFJaWlVjMWcxNnA2RFVMCm1idmt6U0RHbTBvR09iVm8vQ0s2N2xXTUswN3E4N0hqL0xhWm10VkMrbkZOQ00rSEhtcHhmZm5UdE9tbGNZRjcKd2s1SGxxWDJkb1dqS0kvcGdHNkJVNlZ0WDdoSStjTDVOcVl1U2YrNGxzS01CN09iaUZqODZ4c2MzaTF3NHBlUwpNS0dKNDd4VnFDZldTKzJRcll2Nll5VlpMYWcxM2NxWE03emx6Y2VkMGV6dlhnNUtrQVltWTYyNTJUVXRCN3AyClpTeXNWNDk5OUFlVTE0RUNsbDJqQjBuVmV0QlgrUnZuVTBaMXFyQjVRc3RvY1FqcFlMMDVhYzcwcjhOV1FNZXQKVXFJSjVHK0dSNG9mNnlnblhZTWdyd1RKYkZhYWkwYjFBZ01CQUFHamdZTXdnWUF3RHdZRFZSMFRBUUgvQkFVdwpBd0VCL3pBT0JnTlZIUThCQWY4RUJBTUNBUVl3SFFZRFZSME9CQllFRlBkOXhmM0U2Sm9iZDJTbjlSMmd6TCtICllKcHRNRDRHQTFVZElBUTNNRFV3TXdZRVZSMGdBREFyTUNrR0NDc0dBUVVGQndJQkZoMW9kSFJ3T2k4dmQzZDMKTG1ObGNuUXVabTV0ZEM1bGN5OWtjR056THpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQUI1QkszL01qVHZERApuRkZsbTV3aW9vb01oZk56S1d0Ti9nSGlxUXhqQWI4RVo2V2RtRi85QVJQNjdKcGk2WWIrdG1MU2JreVUrOEIxClJYeGxEUGl5Tjgrc0Q4K05iL2taOTQvc0h2SndudkRLdU8rMy8zWTNkbHYyYm9qenIySXlJcE1OT21xT0ZHWU0KTFZOMFYyVWUxYkxkSTRFN3BXWWpKMmNKaitGM3FrUE5aVkVJN1ZGWS91WTUrY3RIaEtRVjhYYTdwTzZrTzhSZgo3N0l6bGhFWXQ4bGx2aGpobzZUYytoajUwN3dUbXpsNk5MclRRZnY2TW9vcXR5dUdDMm1ET0w3TmlpNExjSzJOCkpwTHVIdlVCS3dyWjFwZWJidUNvR1J3NklZc01Ia0N0QStmZFpuNzF1U0FOQStpVytZSkYxRG5nb0FCZDE1am0KZlo1bmM4T2FLdmVyaTZFNkZPODB2RklPaVppYUJFQ0VIWDVGYVpOWHp1dk8rRkI4VHh4dUJFT2IrZFk3SXhqcAo2bzdSVFVhTjhUdmthc3E2K3lPM20vcVpBU2xhV0ZvdDQvblViUTRtcmNGdU5Md3krQXdGK21XajJ6czNneUxwCjF0eHlNLzFkOGlDOWRqd2oyaWozK1J2cldXVFYzRjl5ZmlEOHpZbTFrR2ROWW5vL1RxMGR3em4rZXZRb0Z0OUIKOWtpQUJkY1BVWG1zRUt2VTdBTm01bXF3dWpHU1FrQnF2anJUY3VGcU4xVzhyQjJWdDJsaDhrT1JkT2FnMHdvawpScUVJcjliYVJSbVcxRk1kVzRSNThNRDNSKytMajhVR3JwMU1ZcDMvUmdUNDA4bTJFQ1ZBZGY0V3FzbEtZSVl2CnV1OHdkK1JVNHJpRW1WaUFxaE9MVVRwUFNQYUx0ck09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
type: Opaque
---
# This is a certificate request for three apps domains using cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mainjobs-poa-cert
spec:
  dnsNames:
    - mainjobs-poa-cert.k8s.local
    - mainjobs-poa-web.k8s.local
    - mainjobs-poa-admin.k8s.local
  secretName: mainjobs-poa-cert
  issuerRef:
    name: acme-cfdns-issuer # Setup here your cert manager issuer name
    kind: ClusterIssuer
---
# This is the Traefik IngressRoute tls options to require and verify client certificates using the FMNT Ceres CA
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: mainjobs-poa-des-clientcert-tls
spec:
  clientAuth:
    secretNames:
      - mainjobs-poa-fmnt-ca # Secret que contiene el certificado de la CA del certificado cliente de la FMNT
    clientAuthType: RequireAndVerifyClientCert
---
# This is the Traefik Middleware to pass the client certificate to the backend in pem format
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mainjobs-poa-des-passtlsclientcert
spec:
  passTLSClientCert:
    pem: true
---
# This is the Traefik IngressRoute for the mainjobs-poa-admin /certificate-access path that requires a client certificate
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mainjobs-poa-des-custom-ingress-cert
spec:
  tls:
    secretName: mainjobs-poa-cert
    options:
      name: mainjobs-poa-des-clientcert-tls
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mainjobs-poa-cert.k8s.local`) && PathPrefix(`/certificate-access`)
      services:
        - name: dc-mainjobs-poa-portal-objetos-aprendizaje-admin-service # The first part of this service name depends on your Helm release name
          port: 80
      middlewares:
        - name: mainjobs-poa-des-passtlsclientcert
---
# These are the ususal Traefik IngressRoutes for the mainjobs-poa-web and mainjobs-poa-admin domains
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mainjobs-poa-des-custom-ingress
spec:
  tls:
    secretName: mainjobs-poa-cert
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mainjobs-poa-web.k8s.local`)
      services:
        - name: dc-mainjobs-poa-portal-objetos-aprendizaje-web-service # The first part of this service name depends on your Helm release name
          port: 80
    - kind: Rule
      match: Host(`mainjobs-poa-admin.k8s.local`)
      services:
        - name: dc-mainjobs-poa-portal-objetos-aprendizaje-admin-service # The first part of this service name depends on your Helm release name
          port: 80