apiVersion: v1
kind: Secret
metadata:
  name: poa-postgresql-secret
type: Opaque
data:
  host: bm90X3VzZWQ=
  user: cG9hX3VzZXI=
  password: IUNoYW5nZU1lIS4xMjMh
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-admin-appkey-secret
type: Opaque
data:
  app_key: YmFzZTY0OnMyZjZEWkFmZVJVR3JuQndvL3dvTURQM0xwOXc0RUxkTzBMRUw1Mzd4SE09
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-web-appkey-secret
type: Opaque
data:
  app_key: YmFzZTY0OnMyZjZEWkFmZVJVR3JuQndvL3dvTURQM0xwOXc0RUxkTzBMRUw1Mzd4SE09
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-admin-web-api-key-secret
type: Opaque
data:
  api_key: Uk9JU21JY2lsRXRpdk9sZXl3RXI=
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-sso-fmnt-hash-salt-secret
type: Opaque
data:
  salt_secret: Uk9JU21JY2lsRXRpdk9sZXl3RXI=
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-admin-saml2-sp-cert-secret
type: Opaque
data:
  x509: TUlJRHRUQ0NBcDJnQXdJQkFnSVVQcVFaVXFEeEhTVFMxak1pV2s1a21WWXRNSFV3RFFZSktvWklodmNOQVFFTEJRQXdnWUl4Q3pBSkJnTlZCQVlUQWtWVE1STXdFUVlEVlFRSURBcFRiMjFsTFZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJEYVhSNU1TRXdId1lEVlFRS0RCaEpiblJsY201bGRDQlhhV1JuYVhSeklGQjBlU0JNZEdReEZqQVVCZ05WQkFzTURVbFVJRVJsY0dGeWRHMWxiblF4RkRBU0JnTlZCQU1NQzJWNFlXMXdiR1V1WTI5dE1CNFhEVEkwTVRFeU9UQTJOVFF6T1ZvWERUSTFNVEV5T1RBMk5UUXpPVm93Z1lJeEN6QUpCZ05WQkFZVEFrVlRNUk13RVFZRFZRUUlEQXBUYjIxbExWTjBZWFJsTVEwd0N3WURWUVFIREFSRGFYUjVNU0V3SHdZRFZRUUtEQmhKYm5SbGNtNWxkQ0JYYVdSbmFYUnpJRkIwZVNCTWRHUXhGakFVQmdOVkJBc01EVWxVSUVSbGNHRnlkRzFsYm5ReEZEQVNCZ05WQkFNTUMyVjRZVzF3YkdVdVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXh3OWhCNGN6UExrSjJBdkJRL252dVVsK09aRW5vSEdKbW1wYkl1Y1BTR3Y0cGFrR2ZhVGtoNlVhU1Q5dFpLRWhYbEVlTDRDejdTdUhMSThRTUsweTdocXErb1NTdU83K1l3Rjk1L3Baelhrbk9BbzN2Sit5dmVuTEZMK01pakIwVTBGemN6RmwzNDVzajY1K2dpWlFrK1FsL3ZLK215bGtuSzQ1NnhkRUJhQTNFK1VoeFpBd2JITElxbTAxVmVFOThZU0ZidmNzbW11ZU95TXdIOGhKN1BoOTBTdUV6cVNuQ1p3N0FWNS9RVVFrWFRWMWpjQ09wUnl3Z1RYMUhlZDBLSVEwbmE4bVJ4NGlpanQwdFVFWUwyTjdZMUYyNFpVdzRSOVdOdWxnUHZNOURBWHRLVVJiSDR1eHVpNDV0WTd1MnZZMXJxRm9qeVZwclkvM2NHKzJUUUlEQVFBQm95RXdIekFkQmdOVkhRNEVGZ1FVZEZna0RLZjhEaUsrQWJHVFNua1ZoSWlRMCtJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGQ2RIU3R4ZzdUeHc5SVBQOWZzQ3NIYTNSOHRENkZvTFdEWDNXZUY4RDJLSUc4WlJmZ0hNaGNRT0dOVktzekdlK0ZnOWZEQ3A4dDBEK1hVZGl5ektDRVdFWDYvclF6cEdmODhZREc3Y2ZSVzJmRGV5K3FLUkYxVmhzN0s1a3l0aEw2TndZSGNlQzRHbTloRWZZL1VsOS96cC9oK1MvT0RtRzE4QVpBTEJsWmlhWVFQN3pVLzR5T2c1RnpKN1JQd2tML1ZmUzIxUi9ERjZjM0ZzOVlodGM1TlVXOWZKM0ZHaTVRUkNzWWtmVEtJVllwZ1JQeC9tUW1yRWQ0UjRSOEEybndiSmQydnpHbU0wZC9mQ1NaQUtub2xpVFI1alc0SnE4b3EvczFSOXBqN2dkMmNvRFJtazNuN2xqV3ZHWHJ2NHlER1J2bzZMdWxYdGZaMkl2MndBbnc9
  private_key: TUlJRXBBSUJBQUtDQVFFQXh3OWhCNGN6UExrSjJBdkJRL252dVVsK09aRW5vSEdKbW1wYkl1Y1BTR3Y0cGFrR2ZhVGtoNlVhU1Q5dFpLRWhYbEVlTDRDejdTdUhMSThRTUsweTdocXErb1NTdU83K1l3Rjk1L3Baelhrbk9BbzN2Sit5dmVuTEZMK01pakIwVTBGemN6RmwzNDVzajY1K2dpWlFrK1FsL3ZLK215bGtuSzQ1NnhkRUJhQTNFK1VoeFpBd2JITElxbTAxVmVFOThZU0ZidmNzbW11ZU95TXdIOGhKN1BoOTBTdUV6cVNuQ1p3N0FWNS9RVVFrWFRWMWpjQ09wUnl3Z1RYMUhlZDBLSVEwbmE4bVJ4NGlpanQwdFVFWUwyTjdZMUYyNFpVdzRSOVdOdWxnUHZNOURBWHRLVVJiSDR1eHVpNDV0WTd1MnZZMXJxRm9qeVZwclkvM2NHKzJUUUlEQVFBQkFvSUJBRTMybEFZaXljcUtublJqaGpwZGRhcVlRanZCd2tkd3NIZ3VGNnUvMjVoOTBWRHd0bjRYU3ZwbGk3b01nWWZjSS9tUXc4WFBIcWxSVnd2NHJGcWtPMEpPWjVEZXc2aHkwbWRzZWllVlFmN2I2S1JtUEJaQVpmMUR5Q3BFSzRNa0h5dE1neThtdGNPdFFJKzF4QTZ0ZXZteGJjQkF5cTV5czlrNTA2MWoyMXhvQmt0TWdKYisvTFFIa21aMng3WmNyalhUR0hXMGQ4M1pIQlpES0lDRnpVTUU3SVNPMTlDdHNCemV5Qm4ycjN4ZHdwelVjZUNkaHNidzVwT1c3N1NVNlBGM01rcUNsRWRjdXZXWmxrd3BVL3U1UG5LVEQzMU4xSWNkMUo2dUxxUTFyRG95TU8rVFdHQk91d2xoOWcwK0gzaUMzZHd6cXpVelBkT21kc0E1OC9FQ2dZRUE5Qi9IV2F2ZlllUUhDWnA4Uk84WkVwbDdhZlQ5UDNaZUN5di9DT3N4Qko4aFM5dnlWVWY4WThaZ2toaU8yRUxDQktVK2lqcHZWQ20raTRnVkhWUWgrV3kvTmhKZTBCbHJ0ZnlRVllBZ29jQnZQOVJPRFcxU25OaHZodWU2Vm5kZytVbVBEVFQ4S0t3QWZ6am9yUzZEMFJqSGRWaFpyT1pQdWRKa3JsVG9EMHNDZ1lFQTBMNWtIYTJWQU8zSjg2bUZlNVNUaXhxK3pVYTBCRllIK0ZFRGlEc2NUSzBnS251aCs4bklzRTZ4azYycEQzSTZmQUh2L1pZYkdTcHRETFp6UldIQzgyM2E1Z2hBMUhheFowM1ZJWitseVh0MzhPc3hna084VzBGYVI1V3dQZVd3TGt4R0xFRCsxUnBQU0hJUDVhaWg2SmZwV2hrUlNKaXhidGNFWjZPNG1jY0NnWUJkVDVCSkxETFVIZTY2c3Z2dzlWc21DdGhyWmFNdkVMVmRtOUY5dlRnZFJoM1oreFlqbHNKWCtNbU16aW83YXpqeHdaK29Bakh2ZjQwL2xDSk45WXlPNUF3cVJOZE12NHEySXZXZ1dMc2dXSWV0WkI3NWJ1SDI1WnVyZXdOMGJXajVvQzQzcEJzR0NNaWYyRWJIZTFJVEtGK0U4T0pGL2pwWEVwNDlMR01QQlFLQmdRQ0dzVk9Ja3VrQ29HMGZmTk5VMnBvWnVEaEYzTWxyd3RlQnMwVEVNdUFmMmRaWGswOENXVUhXQWZFemlXcjlQSWZnWEordTBaektzRVdOWG0waTUrSVRrVjhkNzFWbHd2RFY1N01PN3lUYXpZQ25SQnUrSWxiM3kwT2x6VURicjhudkZlaHh4YjZwWTBDbFRuUlRqR3hzMlJrSnVnTWRCT240eTJWY09waHpJUUtCZ1FEU3pBZGx0YktOdjdLcEkxaWRaYlZZb0pqbzB0L2V0TlZLQkp3bUZyY0tPbXRZaG9pbUtkLytCUmtESFF1Y0pCNXdhL285bTdlRWhhMkdwTEFoU2NCUkp0akhNajlHcUhLazA1MTVoZjg3dlFOK0o0UGVWMjZPK29GaS9DbUpjNUMzTVhGaXNCdHBON3FEaURScmpHbGNGMkN5dGt2M0RNVnNFdVhNaXRIOHdnPT0=
