apiVersion: v1
kind: Secret
metadata:
  name: poa-mysql-secret
type: Opaque
data:
  host: bm90X3VzZWQ=
  user: cG9hX3VzZXI=
  password: IUNoYW5nZU1lIS4xMjMh
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-admin-appkey-secret
type: Opaque
data:
  app_key: YmFzZTY0OnMyZjZEWkFmZVJVR3JuQndvL3dvTURQM0xwOXc0RUxkTzBMRUw1Mzd4SE09
---
apiVersion: v1
kind: Secret
metadata:
  name: poa-web-appkey-secret
type: Opaque
data:
  app_key: YmFzZTY0OnMyZjZEWkFmZVJVR3JuQndvL3dvTURQM0xwOXc0RUxkTzBMRUw1Mzd4SE09
